# Labo Ansible - Test n° 2

NETWORK_PREFIX = "192.168.56"

Vagrant.configure("2") do |config|

  config.vm.define "rocky" do |rocky|
    rocky.vm.box = "generic/rocky9"
    rocky.vm.hostname = "rocky"
    rocky.vm.network :private_network, ip: "#{NETWORK_PREFIX}.10"
    rocky.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    rocky.vm.provider "virtualbox" do |vbox|
      vbox.memory = 1024
      vbox.cpus = 2
      vbox.check_guest_additions = false
    end
  end

  config.vm.define "suse" do |suse|
    suse.vm.box = "generic/opensuse15"
    suse.vm.hostname = "suse"
    suse.vm.network :private_network, ip: "#{NETWORK_PREFIX}.20"
    suse.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    suse.vm.provider "virtualbox" do |vbox|
      vbox.memory = 1024
      vbox.cpus = 2
      vbox.check_guest_additions = false
    end
  end

  config.vm.define "debian" do |debian|
    debian.vm.box = "generic/debian12"
    debian.vm.hostname = "debian"
    debian.vm.network :private_network, ip: "#{NETWORK_PREFIX}.30"
    debian.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    debian.vm.provider "virtualbox" do |vbox|
      vbox.memory = 1024
      vbox.cpus = 2
      vbox.check_guest_additions = false
    end
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "bento/ubuntu-22.04"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.network :private_network, ip: "#{NETWORK_PREFIX}.40"
    ubuntu.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    ubuntu.vm.provider "virtualbox" do |vbox|
      vbox.memory = 1024
      vbox.cpus = 2
      vbox.check_guest_additions = false
    end
  end

end
