---  # command4.yml

- hosts: debian
  gather_facts: false

  tasks:

    - name: Report root partition space usage
      command: df -h /
      changed_when: false
      register: df_cmd

    - debug:
        msg: "{{df_cmd}}"

...
