---  # hello-debian.yml

- hosts: all

  tasks:

    - name: Check if target host is a Debian-based system
      debug:
        msg: "This is a Debian-based system."
      when: ansible_os_family == "Debian"

...
