# Labo Ansible - Atelier n° 4

NETWORK_PREFIX = "192.168.56"

Vagrant.configure("2") do |config|

  config.vm.define "debian" do |debian|
    debian.vm.box = "generic/debian12"
    debian.vm.hostname = "debian"
    debian.vm.network :private_network, ip: "#{NETWORK_PREFIX}.10"
    debian.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    debian.vm.provider "virtualbox" do |vbox|
       vbox.memory = 1024
       vbox.cpus = 2
       vbox.check_guest_additions = false
    end
  end

  config.vm.define "rocky" do |rocky|
    rocky.vm.box = "generic/rocky9"
    rocky.vm.hostname = "rocky"
    rocky.vm.network :private_network, ip: "#{NETWORK_PREFIX}.20"
    rocky.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    rocky.vm.provision "shell", path: "setup-rocky.sh"
    rocky.vm.provider "virtualbox" do |vbox|
       vbox.memory = 1024
       vbox.cpus = 2
       vbox.check_guest_additions = false
    end
  end

end
